### ISSUE TITLE
ui - user can not stop processes

### ISSUE THREAD

**Issue by Laurira** [keeps/dbptk-ui#274]
Sometimes validation or preparation can become stuck so that for example DBPTK Enterprise shows "Preparing". The log is full of errors (it has worked 2 days) and actually this process will probably never be finished so user should have a possibility to stop the started process.

At the moment when user clicks "DELETE" for this database that is stuck then it says "Please wait for the current process to finish".
![image](https://user-images.githubusercontent.com/3479156/115345967-375f9f00-a1b8-11eb-8885-b2e543e78daf.png)

**Comment by luis100** [comment]
This should be fixed by moving SIARD loading to a Spring Batch job.

**Comment by Laurira** [comment]
Just reminding that this is still not fiexed and it is very annoying issue. Sometimes the indexing process get stuck and user wants to remove the siard from the dbptk and re-load and re-index it. At the moment it is not possible. Please let us know when this is fixed.
